# Generated by Django 3.1.7 on 2021-06-16 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Название')),
                ('slug', models.CharField(blank=True, editable=False, max_length=250, null=True, verbose_name='Иденитификатор')),
            ],
            options={
                'verbose_name': 'Группа атрибутов',
                'verbose_name_plural': 'Группы атрибутов',
            },
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('slug', models.CharField(blank=True, editable=False, max_length=250, null=True, verbose_name='Иденитификатор')),
                ('full_slug', models.CharField(blank=True, editable=False, max_length=500, null=True, verbose_name='Иденитификатор')),
            ],
            options={
                'verbose_name': 'Атрибут',
                'verbose_name_plural': 'Атрибуты',
            },
        ),
        migrations.CreateModel(
            name='CategoryAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_pk', models.PositiveIntegerField(default=0, editable=False)),
            ],
            options={
                'verbose_name': 'Связь атрибутов с категрией',
                'verbose_name_plural': 'Связи атрибутов с категриями',
            },
        ),
        migrations.CreateModel(
            name='CategoryAttributeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Атрибут категрии',
                'verbose_name_plural': 'Атрибуты категрий',
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_attrs', to='filters.categoryattribute')),
            ],
            options={
                'verbose_name': 'Атрибуты товара',
                'verbose_name_plural': 'Атрибуты товаров',
                'ordering': ['-attribute__attribute__name'],
            },
        ),
    ]
