# Generated by Django 3.1.7 on 2021-07-03 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        ('opt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('email_confirmed', models.BooleanField(blank=True, default=False)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('phone_confirmed', models.BooleanField(blank=True, default=False)),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='Фамилия')),
                ('father_name', models.CharField(blank=True, max_length=30, verbose_name='Отчество')),
                ('country', models.CharField(blank=True, max_length=30, verbose_name='Страна')),
                ('city', models.CharField(blank=True, max_length=30, verbose_name='Город')),
                ('is_whoosaler', models.BooleanField(default=False, verbose_name='Оптовый покупатель')),
                ('want_be_whoosaler', models.BooleanField(default=False, verbose_name='Хочет продавать оптом')),
                ('real_stock', models.BooleanField(default=True, verbose_name='Покупать по реальному остатку')),
                ('certificate', models.FileField(blank=True, null=True, upload_to='certificate', verbose_name='Сертификат')),
                ('passport', models.FileField(blank=True, null=True, upload_to='passport', verbose_name='Удостоверение личноти')),
                ('password', models.CharField(blank=True, max_length=500)),
                ('was_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False, verbose_name='Администратор')),
                ('is_active', models.BooleanField(default=False, verbose_name='Аккаунт активирован')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='UserAdress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=500, verbose_name='Город')),
                ('street', models.CharField(max_length=500, verbose_name='Улица')),
                ('house', models.CharField(max_length=500, verbose_name='Дом')),
                ('appartment', models.CharField(max_length=500, verbose_name='Квартира / Офис')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserNP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=500)),
                ('branch', models.CharField(max_length=500)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='np', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscripton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ManyToManyField(related_name='subscription', to='shop.Categories')),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Подписка на категории',
                'verbose_name_plural': 'Подписка на категории',
            },
        ),
        migrations.CreateModel(
            name='UserNPChosen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.usernp')),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='np_chosen', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название')),
                ('code', models.CharField(blank=True, max_length=500, verbose_name='ЕДРПОУ')),
                ('position', models.CharField(blank=True, max_length=500, null=True, verbose_name='Должность')),
                ('company', models.CharField(blank=True, max_length=500, null=True, verbose_name='Организация')),
                ('email', models.EmailField(max_length=500, null=True, unique=True, verbose_name='Корпоративный E-mail')),
                ('iban', models.CharField(blank=True, max_length=500, verbose_name='Номер счета (IBAN)')),
                ('director', models.CharField(blank=True, max_length=500, verbose_name='ФИО Директора')),
                ('adress', models.CharField(blank=True, max_length=500, verbose_name='Юридический адрес')),
                ('business_type', models.ManyToManyField(blank=True, to='opt.BusinessTypes', verbose_name='Тип бизнеса')),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAdressChosen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.useradress')),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adress_chosen', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
