# Generated by Django 3.1.7 on 2021-07-22 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercompany',
            options={'verbose_name': 'Компания', 'verbose_name_plural': 'Компания'},
        ),
    ]
