# Generated by Django 3.1.7 on 2021-06-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='real_stock',
            field=models.BooleanField(default=True, verbose_name='Покупать по реальному остатку'),
        ),
    ]
