# Generated by Django 3.1.7 on 2021-06-16 13:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.CharField(blank=True, max_length=255, verbose_name='Тип бизнеса')),
                ('business_custom', models.CharField(blank=True, max_length=255, verbose_name='Тип бизнеса (свой вариант)')),
                ('brand_work', models.CharField(blank=True, max_length=255, verbose_name='Бренды с которыми работаю')),
                ('brand_i_want', models.CharField(blank=True, max_length=255, verbose_name='Бренды с которыми хочу работать')),
                ('budjet_clien', models.CharField(blank=True, max_length=255, verbose_name='Бюджет клиента')),
                ('budjet_month', models.CharField(blank=True, max_length=255, verbose_name='Бюджет на закупку')),
                ('gift', models.CharField(blank=True, max_length=255, verbose_name='Подарок')),
                ('gift_custom', models.CharField(blank=True, max_length=255, verbose_name='Подарок (свой вариант)')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(blank=True, max_length=255, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='WhoosaleText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Текст для оптовго покупателя',
                'verbose_name_plural': 'Текст для оптовго покупателя',
            },
        ),
    ]
