# Generated by Django 3.1.7 on 2021-07-03 12:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessDifficulties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('slug', models.CharField(blank=True, max_length=250, null=True, verbose_name='Иденитификатор')),
            ],
            options={
                'verbose_name': 'Quiz: Трудности',
                'verbose_name_plural': 'Quiz: Трудности',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BusinessPositions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('slug', models.CharField(blank=True, max_length=250, null=True, verbose_name='Иденитификатор')),
            ],
            options={
                'verbose_name': 'Quiz: Должность',
                'verbose_name_plural': 'Quiz: Должности',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BusinessTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('slug', models.CharField(blank=True, max_length=250, null=True, verbose_name='Иденитификатор')),
            ],
            options={
                'verbose_name': 'Quiz: Вид бизнеса',
                'verbose_name_plural': 'Quiz: Виды бизнеса',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WhoosaleText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Текст для оптовго покупателя',
                'verbose_name_plural': 'Текст для оптовго покупателя',
            },
        ),
    ]
