# Generated by Django 3.1.7 on 2021-07-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('en', 'ENG'), ('ru', 'РУС'), ('uk', 'УКР')], max_length=10, unique=True)),
                ('name', models.CharField(blank=True, max_length=250)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Активный язык',
                'verbose_name_plural': 'Активные языки',
            },
        ),
    ]
