# Generated by Django 3.1.7 on 2021-06-16 13:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestData1C',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата загрузки')),
                ('data', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Сохраненный запрос 1С сервера',
                'verbose_name_plural': 'Сохраненные запросы 1С сервера',
            },
        ),
        migrations.CreateModel(
            name='RequestData1CSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=255, verbose_name='IP адрес')),
            ],
            options={
                'verbose_name': 'Допустимый IP',
                'verbose_name_plural': 'Допустимые IP',
            },
        ),
    ]
