# Generated by Django 3.1.7 on 2021-06-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync1c', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestdata1csettings',
            name='ip',
            field=models.CharField(max_length=255, unique=True, verbose_name='IP адрес'),
        ),
    ]
