# Generated by Django 3.1.7 on 2022-07-22 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210703_1845'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPostTranslation',
        ),
    ]
