# Generated by Django 3.1.7 on 2023-03-26 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogposttranslation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPostTranslation',
        ),
    ]
