# Generated by Django 3.1.7 on 2021-07-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210703_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_cost',
            field=models.CharField(default=0, max_length=255, verbose_name='Стоисомть доставки'),
        ),
    ]
