# Generated by Django 3.1.7 on 2021-07-22 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20210703_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reference',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
