# Generated by Django 3.1.7 on 2021-06-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_whoosale'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('newpost', 'Новая почта'), ('curier', 'Адресная доставка')], default='np', max_length=255, verbose_name='Способ доставки'),
            preserve_default=False,
        ),
    ]
