# Generated by Django 3.1.7 on 2022-12-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay_type',
            field=models.CharField(choices=[('np', 'Наложеный платежь'), ('card', 'Оплата картой на сайте'), ('cash', 'Наличными при получении'), ('prepayment', 'Передоплата 200 грн')], max_length=255, verbose_name='Способ оплаты'),
        ),
    ]
