# Generated by Django 3.1.7 on 2023-03-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код промокоду')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Сума знижки у відсотках')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоди',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='pay_type',
            field=models.CharField(choices=[('np', 'Наложеный платежь'), ('card', 'Оплата картой на сайте'), ('cash', 'Наличными при получении'), ('prepayment', 'Передоплата 200 грн')], max_length=255, verbose_name='Способ оплаты'),
        ),
    ]
