# Generated by Django 3.1.7 on 2021-06-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_delivery_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentresponses',
            name='response',
            field=models.JSONField(default=dict),
        ),
    ]
