# Generated by Django 3.1.7 on 2023-04-02 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20230327_1735'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PromoCode',
        ),
    ]
