# Generated by Django 3.1.7 on 2022-07-28 13:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210703_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='descendants',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1024), default=list, size=None),
        ),
    ]
