# Generated by Django 3.1.7 on 2022-10-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_categories_descendants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='advantages',
            field=models.CharField(blank=True, max_length=1200, null=True, verbose_name='Переваги'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='disadvantages',
            field=models.CharField(blank=True, max_length=1200, null=True, verbose_name='Недоліки'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rate',
            field=models.PositiveIntegerField(blank=True, choices=[(5, 5), (4, 4), (3, 3), (2, 2), (1, 1)], default=5, null=True, verbose_name='Оцініть товар'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Коментар'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Коментар'),
        ),
    ]
