# Generated by Django 3.1.7 on 2022-10-27 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20221006_1106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variant',
            options={'ordering': ['-price', '-stock'], 'verbose_name': 'Продукт: Вариант', 'verbose_name_plural': 'Продукт: Варианты'},
        ),
    ]
