# Generated by Django 3.1.7 on 2022-12-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20221028_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='stock',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Остаток'),
        ),
    ]
