# Generated by Django 3.1.7 on 2023-04-02 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_promocode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PromoCode',
        ),
    ]
