# Generated by Django 3.1.7 on 2022-07-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20210705_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontacts',
            name='email',
            field=models.EmailField(blank=True, max_length=500, null=True, verbose_name='Email'),
        ),
    ]
