# Generated by Django 3.1.7 on 2022-08-20 15:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20220820_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagedelivery',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, max_length=500, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='pagetermsofuse',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, max_length=500, null=True, verbose_name='Текст'),
        ),
    ]
