# Generated by Django 3.1.7 on 2022-08-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20220820_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagetermsofuse',
            name='text',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Текст'),
        ),
    ]
