# Generated by Django 3.1.7 on 2022-08-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20220820_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagetermsofuse',
            name='text',
            field=models.CharField(default='text', max_length=1000),
        ),
    ]
