# Generated by Django 3.1.7 on 2022-08-20 16:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20220820_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagetermsofuse',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст'),
        ),
    ]
