# Generated by Django 3.1.7 on 2023-01-10 08:31

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20220909_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageReturnProd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translate_childs', models.BooleanField(default=False, verbose_name='Перевод')),
                ('title', models.CharField(default='Повернення', max_length=255, verbose_name='Заголовок')),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Страница: Повернення',
                'verbose_name_plural': 'Страница: Повернення ',
            },
        ),
    ]
