# Generated by Django 3.1.7 on 2021-06-16 13:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('translate_childs', models.BooleanField(default=False, verbose_name='Перевод')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num', models.PositiveIntegerField(default=0, verbose_name='№')),
                ('image_thmb', models.JSONField(blank=True, default=dict, null=True)),
                ('title', models.CharField(blank=True, max_length=1024, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.FileField(max_length=1024, upload_to='', verbose_name='Баннер')),
                ('link', models.CharField(blank=True, max_length=1024, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата загрузки')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
                'ordering': ('-date',),
            },
        ),
    ]
