# Generated by Django 3.1.7 on 2021-06-23 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_auto_20210623_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannermobile',
            name='parent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mobile', to='banners.banner'),
        ),
        migrations.AlterField(
            model_name='bannerpc',
            name='parent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pc', to='banners.banner'),
        ),
    ]
