# Generated by Django 3.1.7 on 2021-07-03 12:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='office.fortisbeauty@gmail.com', max_length=254)),
                ('adress', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Основная информация',
                'verbose_name_plural': 'Основная информация',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема письма')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Время отправки')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('email', models.CharField(max_length=255, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=255, verbose_name='Телефон')),
                ('text', models.TextField(verbose_name='Текст письма')),
            ],
            options={
                'verbose_name': 'Сообщения',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='OurAdvantages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translate_childs', models.BooleanField(default=False, verbose_name='Перевод')),
                ('num', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name': 'Наши преимущества',
                'verbose_name_plural': 'Наши преимущества',
                'ordering': ['num'],
            },
        ),
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num', models.PositiveIntegerField(default=0, verbose_name='№')),
                ('image', models.FileField(blank=True, max_length=1024, null=True, upload_to='', verbose_name='Изображение')),
                ('image_thmb', models.JSONField(blank=True, default=dict, null=True)),
                ('name', models.CharField(max_length=50, verbose_name='Оператор')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('phone_nums', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Номера телефонов',
                'verbose_name_plural': 'Номера телефонов',
            },
        ),
        migrations.CreateModel(
            name='Slogan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translate_childs', models.BooleanField(default=False, verbose_name='Перевод')),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Слоган на гоавной странице',
                'verbose_name_plural': 'Слоган на гоавной странице',
            },
        ),
    ]
