# Generated by Django 3.1.7 on 2022-10-06 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220924_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ouradvantages',
            name='text',
        ),
        migrations.RemoveField(
            model_name='ouradvantages',
            name='title',
        ),
        migrations.CreateModel(
            name='OurAdvantagesImg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num', models.PositiveIntegerField(default=0, verbose_name='№')),
                ('image_thmb', models.JSONField(blank=True, default=dict, null=True)),
                ('image', models.FileField(max_length=1024, upload_to='', verbose_name='Изображение')),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Image', to='main.ouradvantages')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
