# Generated by Django 3.1.7 on 2022-10-06 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20221006_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ouradvantagesimg',
            name='parent',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='main.ouradvantages'),
        ),
    ]
