# Generated by Django 3.1.7 on 2022-10-07 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20221006_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurAdvantagesMobile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num', models.PositiveIntegerField(default=0, verbose_name='№')),
                ('image_thmb', models.JSONField(blank=True, default=dict, null=True)),
                ('image', models.FileField(max_length=1024, upload_to='', verbose_name='Изображение Мобильный')),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mobile', to='main.ouradvantages')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OurAdvantagesPC',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num', models.PositiveIntegerField(default=0, verbose_name='№')),
                ('image_thmb', models.JSONField(blank=True, default=dict, null=True)),
                ('image', models.FileField(max_length=1024, upload_to='', verbose_name='Изображение')),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pc', to='main.ouradvantages')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='OurAdvantagesImg',
        ),
    ]
