# Generated by Django 3.1.7 on 2021-06-16 13:01

import apps.productloader.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoadProductsFromTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='', max_length=255, verbose_name='Навзвание бренда')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата загрузки')),
                ('table', models.FileField(upload_to=apps.productloader.models.FilePath, validators=[apps.productloader.models.validate_xlsx], verbose_name='XLSX таблица товаров')),
                ('table_old_path', models.CharField(blank=True, editable=False, max_length=2500, null=True)),
            ],
            options={
                'verbose_name': 'Загрузка товаров из таблицы',
                'verbose_name_plural': 'Загрузка товаров из таблицы',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='LoadProductsImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='', max_length=255, verbose_name='Навзвание бренда')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата загрузки')),
                ('rar', models.FileField(upload_to=apps.productloader.models.FilePath, validators=[apps.productloader.models.validate_rar], verbose_name='RAR архив с картинками товаров')),
                ('path', models.CharField(blank=True, max_length=2500, null=True)),
                ('log_rar', models.TextField(blank=True, default='', verbose_name='Ошибка разархивации')),
                ('log_skiped', models.TextField(blank=True, default='', verbose_name='Уже существуют')),
                ('log_loaded', models.TextField(blank=True, default='', verbose_name='Загружено')),
                ('log_error', models.TextField(blank=True, default='', verbose_name='Ошибка файла')),
            ],
            options={
                'verbose_name': 'Загрузка изображений',
                'verbose_name_plural': 'Загрузка изображений',
                'ordering': ('-date',),
            },
        ),
    ]
