# Generated by Django 3.1.7 on 2021-07-15 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productloader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadproductsimages',
            name='log_photo',
            field=models.TextField(blank=True, default='', verbose_name='Товары без фото'),
        ),
    ]
